### ISSUE TITLE
error during cli setup

### ISSUE THREAD

**Issue by thePegasusai** [facebookresearch/playtorch#36] opened 2022-01-23 16:50 UTC
### Problem Area

CLI

### Steps to Reproduce

 Error project "MyFirstProject" is created but we ran into the following i…
    ‎ ‎ ‎ ‎
    ERROR: Could not find a version that satisfies the requirement torch==1.1…
    ERROR: No matching distribution found for torch==1.10.0
    ‎ ‎ ‎ ‎
    please rerun
    ‎ ‎ ‎ ‎ • "python make_models.py" in the MyFirstProject/models/ directory…
    ‎ ‎ ‎ ‎ • "pod install" in the MyFirstProje
![Screen Shot 2022-01-23 at 10 49 15 AM](https://user-images.githubusercontent.com/82119277/150688906-49f97c7a-f0f3-48ce-b265-57433aa49f2c.png)
ct/ios/ directory
    if the issue persists, please report at https://github.com/pytorch/live

### Expected Results

I was hoping to be able to install all necessary requirements via cli command prompt

**Comment by aaronespasa** [comment] 2022-01-23 18:27
Hi @thePegasusai ,

Could you share what's the output when you execute on terminal the command `python3 -V`?

**Comment by thePegasusai** [comment] 2022-01-23 18:34
@aaronespasa imanjefferson@Imans-Air ~ % python3 - v
Python 3.9.9 (v3.9.9:ccb0e6a345, Nov 15 2021, 13:06:05) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by raedle** [comment] 2022-01-26 01:58
@thePegasusai, can you help us narrow down the root cause? Please verify that the Python environment is able to install all dependencies and export (i.e., make) the models! The following steps must succeed, and if they don't, please report the error message:

Navigate to the models directory of your initialized PyTorch Live project:
```
cd MyFirstProject/models
```

Set up a Python3 virtual environment:
```
python3 -m venv venv
```

Activate the virtual environtment:
```
source venv/bin/activate
```

Install dependencies:
```
pip install -r requirements.txt
```

Export (make) models:
```
python make_models.py
```

For context: these steps are executed as part of the `npx torchlive-cli init MyFirstProject` command, but based on your report, one of these steps failed on your machine

**Comment by thePegasusai** [comment] 2022-01-26 02:24
(venv) imanjeffersonImans-Air models % pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement torch==1.10.0 (from versions: none)
ERROR: No matching distribution found for torch==1.10.0

**Comment by chrisklaiber** [comment] 2022-09-16 23:08
Hello @thePegasusai, I'm closing out this issue because the CLI has been removed from PlayTorch. Feel free to re-open if you need additional support.

With the latest PyTorch, you should not need to build the models any longer as part of setup, and the CLI is not required to set up a development environment.

We have release the PlayTorch app and a local development environment is no longer necessary. See https://playtorch.dev/docs/tutorials/get-started/

If you do want to set up a local development environment, we recommend the default approach from React Native or Expo, applied to PlayTorch. See https://playtorch.dev/docs/tutorials/get-started-manually/

**Closed by chrisklaiber** 2022-09-16 23:08 UTC
Labels: 💻  cli
