### ISSUE TITLE
How to detect objects Real Time

### ISSUE THREAD

**Issue by dongdv95** [facebookresearch/playtorch#33] opened 2022-01-10 03:21 UTC
### Description

Pytorch is amazing,thank you for the work you are doing.
I'm trying Object detection example from tutorial , Can you give an example of real time use "onFrame" of CAMERA?

### Website

https://pytorch.org/live/docs/tutorials/get-started/

**Comment by aaronespasa** [comment] 2022-01-10 10:51
Hey @dongdv95,

Take a look at the following example: [ObjectDetectionExample.tsx](https://github.com/pytorch/live/blob/main/react-native-template-pytorch-live/template/src/examples/ObjectDetectionExample.tsx). In this example, you can learn how to perform object detection with [DETR](https://github.com/facebookresearch/detr). The problem is that it's a transformer so it's not meant to work on real-time because it has too many parameters.

You can use a "lighter" model (with less parameters) like the Faster R-CNN (for the moment, you may experiment some issues if you try to use YOLO, that's why I recommend you that model). You can learn how to import this custom model in the following tutorial: [PyTorch Live: Prepare Custom Model](https://pytorch.org/live/docs/tutorials/prepare-custom-model/).

To import the model in the `make_models.py` file you can use `torchvision`:
```py
torchvision.models.detection.faster_rcnn
```
You can see more details about this model in the following link: [torchvision faster_rcnn](https://pytorch.org/vision/stable/_modules/torchvision/models/detection/faster_rcnn.html)

Finally, to adapt the example so it works in real-time you can follow the [Image Classification tutorial](https://pytorch.org/live/docs/tutorials/image-classification/) which covers how to perform image classification in real-time.

Just to summarise, if you only want to see an example of a real-time use of "onFrame" you can just take a look at the Image Classification tutorial and you will see. But I also wanted to show you an example that implements the drawing of the bounding boxes and how you can import a custom model as I think that it will speed up your creation of the app.

Best of luck!

**Comment by dongdv95** [comment] 2022-01-11 10:09
> Hey @dongdv95,
> 
> Take a look at the following example: [ObjectDetectionExample.tsx](https://github.com/pytorch/live/blob/main/react-native-template-pytorch-live/template/src/examples/ObjectDetectionExample.tsx). In this example, you can learn how to perform object detection with [DETR](https://github.com/facebookresearch/detr). The problem is that it's a transformer so it's not meant to work on real-time because it has too many parameters.
> 
> You can use a "lighter" model (with less parameters) like the Faster R-CNN (for the moment, you may experiment some issues if you try to use YOLO, that's why I recommend you that model). You can learn how to import this custom model in the following tutorial: [PyTorch Live: Prepare Custom Model](https://pytorch.org/live/docs/tutorials/prepare-custom-model/).
> 
> To import the model in the `make_models.py` file you can use `torchvision`:
> 
> ```python
> torchvision.models.detection.faster_rcnn
> ```
> 
> You can see more details about this model in the following link: [torchvision faster_rcnn](https://pytorch.org/vision/stable/_modules/torchvision/models/detection/faster_rcnn.html)
> 
> Finally, to adapt the example so it works in real-time you can follow the [Image Classification tutorial](https://pytorch.org/live/docs/tutorials/image-classification/) which covers how to perform image classification in real-time.
> 
> Just to summarise, if you only want to see an example of a real-time use of "onFrame" you can just take a look at the Image Classification tutorial and you will see. But I also wanted to show you an example that implements the drawing of the bounding boxes and how you can import a custom model as I think that it will speed up your creation of the app.
> 
> Best of luck!

Thanks for ans

**Comment by clarksandholtz** [comment] 2022-01-11 17:18
@dongdv95 when do you get this error? When trying to run the model in a PyTorch Live app?

**Comment by dongdv95** [comment] 2022-01-12 07:52
> @dongdv95 when do you get this error? When trying to run the model in a PyTorch Live app?

Hi @clarksandholtz, When I make model  (model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)) , I get this error , I'm not sure my  live.spec.json is correct.

**Comment by clarksandholtz** [comment] 2022-01-12 22:26
@dongdv95 if this is happening when you are making the model in Python, then the `live.spec.json` isn't being used at all. The `live.spec.json` is only used by PyTorch Live in mobile apps. If you remove all of the code that references the `live.spec.json` you still get the same error.

Looks like there is an issue with the tracing, but I'm not sure what it is.

**Comment by dongdv95** [comment] 2022-01-13 02:00
Thanks @clarksandholtz , I test with another model 
( torchvision.models.detection.ssd300_vgg16(pretrained=True) ) and 
(FasterRCNN(backbone= torchvision.models.mobilenet_v2(pretrained=True).features)), I make model success 
but when run inference on Android with error 
```error
Error: Following ops cannot be found. Check fburl.com/missing_ops for the fix.{torchvision::nms, } ()
Exception raised from print_unsupported_ops_and_throw at ../torch/csrc/jit/mobile/parse_operators.cpp:65 (most recent call first):
(no backtrace available)
```
I’m grateful for your assistance

**Comment by chrisklaiber** [comment] 2022-09-16 23:21
Closing this issue out since the packer / unpacker approach was removed with 0.2.2. Check out the PyTorch-inspired API in the README as an alternative that avoids these issues: https://github.com/facebookresearch/playtorch/tree/main/react-native-pytorch-core#example-usage

As for the unsupported operation, I'd try it again. We have updated the versions of PyTorch and Torchvision used in the PlayTorch app (side note: we have rebranded from PyTorch Live to PlayTorch), and what you need may now be supported. Here is a starting-off point for using the PlayTorch app: https://playtorch.dev/docs/tutorials/get-started/

**Closed by chrisklaiber** 2022-09-16 23:21 UTC

**Comment by nh9k** [comment] 2022-10-06 02:00
Hello @aaronespasa,  Where can i find example of a real-time use of "onFrame"? 
This [Image Classification tutorial link](https://github.com/facebookresearch/playtorch/issues/33#issuecomment-1008751282) is unavailable and I can't find real-time example at [image classification example link](https://playtorch.dev/docs/0.2.0/tutorials/snacks/image-classification/) of playtorch tutorial.
