### ISSUE TITLE
UnhandledPromiseRejection @ npx torchlive-cli run-android in "get started"

### ISSUE THREAD

**Issue by abebe9849** [facebookresearch/playtorch#47] opened 2022-02-26 05:47 UTC
### Tutorial Select

Get Started

### Feedback

when I run these,I got an error

```
(venv) (base) abemasatoshinoMacBook-Air:~ patriot$ npx torchlive-cli init PL_project
  _                 _     _ _           
 | |_ ___  _ __ ___| |__ | (_)_   _____ 
 | __/ _ \| '__/ __| '_ \| | \ \ / / _ \
 | || (_) | | | (__| | | | | |\ V /  __/
  \__\___/|_|  \___|_| |_|_|_| \_/ \___|
                                        
torchlive version 0.1.3
✔ project PL_project
  › Initialized project PL_project
    ‎ ‎ ‎ ‎
    Run instructions for Android:
    ‎ ‎ ‎ ‎ • Have an Android emulator running (quickest way to get started), or a device connected.
    ‎ ‎ ‎ ‎ • cd PL_project && npx torchlive-cli run-android
    ‎ ‎ ‎ ‎
    Run instructions for iOS:
    ‎ ‎ ‎ ‎ • cd PL_project && npx torchlive-cli run-ios
    ‎ ‎ ‎ ‎ - or -
    ‎ ‎ ‎ ‎ • Open PL_project/ios/PL_project.xcworkspace in Xcode or run "xed -b ios"
    ‎ ‎ ‎ ‎ • Hit the Run but
```
and 

```
(venv) (base) abemasatoshinoMacBook-Air:PL_project patriot$ npx torchlive-cli run-android
INFO    | configAndStartRenderer: setting vsync to 60 hz
INFO    | added library /Users/patriot/Library/Android/sdk/emulator/lib64/vulkan/libvulkan.dylib
INFO    | Started GRPC server at 127.0.0.1:8554, security: Local
INFO    | Advertising in: /Users/patriot/Library/Caches/TemporaryItems/avd/running/pid_27722.ini
yarn‎ run‎ v1.22.17
$‎ react-native‎ run-android
info‎ Running‎ jetifier‎ to‎ migrate‎ libraries‎ to‎ AndroidX.‎ You‎ can‎ disable‎ it‎ using‎ "--no-jetifier"‎ flag.
Jetifier‎ found‎ 1182‎ file(s)‎ to‎ forward-jetify.‎ Using‎ 4‎ workers...
info‎ Starting‎ JS‎ server...
info‎ Installing‎ the‎ app...

FAILURE:‎ Build‎ failed‎ with‎ an‎ exception.

*‎ What‎ went‎ wrong:
A‎ problem‎ occurred‎ configuring‎ project‎ ':react-native-pytorch-core'.
>‎ NDK‎ at‎ /Users/patriot/Library/Android/sdk/ndk/20.1.5948944‎ did‎ not‎ have‎ a‎ source.properties‎ file

*‎ Try:
Run‎ with‎ --stacktrace‎ option‎ to‎ get‎ the‎ stack‎ trace.‎ Run‎ with‎ --info‎ or‎ --debug‎ option‎ to‎ get‎ more‎ log‎ output.‎ Run‎ with‎ --scan‎ to‎ get‎ full‎ insights.

*‎ Get‎ more‎ help‎ at‎ https://help.gradle.org

BUILD‎ FAILED‎ in‎ 24s
Error:‎ Command‎ failed:‎ ./gradlew‎ app:installDebug‎ -PreactNativeDevServerPort=8081

FAILURE:‎ Build‎ failed‎ with‎ an‎ exception.

*‎ What‎ went‎ wrong:
A‎ problem‎ occurred‎ configuring‎ project‎ ':react-native-pytorch-core'.
>‎ NDK‎ at‎ /Users/patriot/Library/Android/sdk/ndk/20.1.5948944‎ did‎ not‎ have‎ a‎ source.properties‎ file

*‎ Try:
Run‎ with‎ --stacktrace‎ option‎ to‎ get‎ the‎ stack‎ trace.‎ Run‎ with‎ --info‎ or‎ --debug‎ option‎ to‎ get‎ more‎ log‎ output.‎ Run‎ with‎ --scan‎ to‎ get‎ full‎ insights.

*‎ Get‎ more‎ help‎ at‎ https://help.gradle.org

BUILD‎ FAILED‎ in‎ 24s

‎ ‎ ‎ ‎ at‎ makeError‎ (/Users/patriot/PL_project/node_modules/execa/index.js:174:9)
‎ ‎ ‎ ‎ at‎ /Users/patriot/PL_project/node_modules/execa/index.js:278:16
‎ ‎ ‎ ‎ at‎ processTicksAndRejections‎ (node:internal/process/task_queues:96:5)
‎ ‎ ‎ ‎ at‎ async‎ runOnAllDevices‎ (/Users/patriot/PL_project/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:5)
‎ ‎ ‎ ‎ at‎ async‎ Command.handleAction‎ (/Users/patriot/PL_project/node_modules/@react-native-community/cli/build/index.js:186:9)
info‎ Run‎ CLI‎ with‎ --verbose‎ flag‎ for‎ more‎ details.
info‎ Visit‎ https://yarnpkg.com/en/docs/cli/run‎ for‎ documentation‎ about‎ this‎ command.
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
error Command failed with exit code 1.
".] {
  code: 'ERR_UNHANDLED_REJECTION'
```

**Comment by liuyinglao** [comment] 2022-03-11 22:59
Hi @abebe9849 Thanks for reporting!

could you try to update the NDK version on your macbook to see if that would fix? here is the link if you are using Android Studio: https://developer.android.com/studio/projects/install-ndk#specific-version

Thanks!

**Comment by raedle** [comment] 2022-07-14 04:32
@abebe9849, we cannot reproduce the error. Does the issue still persist for you with the latest release `0.2.0`?

**Comment by chrisklaiber** [comment] 2022-09-16 23:25
Closing out this issue because the CLI has been removed from PlayTorch. Feel free to re-open if you need additional support.

We have released the PlayTorch app and a local development environment is no longer necessary. See https://playtorch.dev/docs/tutorials/get-started/

If you do want to set up a local development environment, we recommend the default approach from React Native or Expo, applied to PlayTorch. See https://playtorch.dev/docs/tutorials/get-started-manually/

**Closed by chrisklaiber** 2022-09-16 23:25 UTC
