### ISSUE TITLE
Pick image from gallery for image classification

### ISSUE THREAD

**Issue by mathewGlenn** [facebookresearch/playtorch#123] opened 2022-09-13 13:51 UTC
### Area Select

Website/Documentation

### Description

Can you please tell me if there is a feature where I can pick image from gallery for the image classification?

**Comment by raedle** [comment] 2022-09-13 21:30
Hi @mathewGlenn, there is the [ImagePicker](https://docs.expo.dev/versions/v44.0.0/sdk/imagepicker/) component from Expo that lets you pick photos from the camera roll.

I created a quick demo based on the Image Classification tutorial:

https://user-images.githubusercontent.com/489051/190012412-378f6549-1b13-43b9-ad56-f04f9b65703d.MP4

PlayTorch Snack to test: https://playtorch.dev/snack/@raedle/image-classification-with-image-picker/

Hope that helps!

**Comment by mathewGlenn** [comment] 2022-09-14 11:10
Thank you. I was using react-native-image-picker but I could not make it work.

**Comment by raedle** [comment] 2022-09-14 16:28
@mathewGlenn, are you trying to use the `react-native-image-picker` with the PlayTorch app or are you trying to use it with a custom React Native app project?

The latter should work with the `react-native-image-picker`. If that's the case, can you share the project or code samples that failed?

Happy to look into it!

**Comment by lavandaboy** [comment] 2022-09-15 11:38
Hi @raedle,

Thanks a lot for your snack. 

Just tested your snack on the new ios 16 using playtorch app. Unfortunately, the gallery button does not work. I press on it and nothing happens. The camera part works perfectly. 

I will appreciate your help.

**Comment by raedle** [comment] 2022-09-15 16:17
@lavandaboy, I verified that the gallery button works on iOS `16.0 (20A362)` on an iPhone 11 Pro. What is the PlayTorch app version that is failing for you?

I am using the latest PlayTorch app version from the App Store with `Application version 0.1.1` and `Build version 6`

![image](https://user-images.githubusercontent.com/489051/190455484-87091b14-3e31-4358-a600-b0b5801ab75c.png)

**Comment by raedle** [comment] 2022-09-16 19:44
@mathewGlenn and @lavandaboy, I'm going to close the issue. Please reopen if the issue is not resolved for you!

**Closed** 2022-09-16 19:44 UTC
