### ISSUE TITLE
Repeated rendering to Canvas crashes app on iOS 

### ISSUE THREAD

**Issue by SomaKishimoto** [facebookresearch/playtorch#115] opened 2022-08-24 03:16 UTC
### Version

0.2.1

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

1. repeat rendering to Canvas

Error message:
`Message from debugger: Terminated due to memory issue`

just before the crush:
`W0821 11:40:23.873222 1881387008 JSIExecutor.cpp:381] Memory warning (pressure level: 1) received by JS VM, unrecognized pressure level`

The crush doesn't occur when  [this commit](https://github.com/facebookresearch/playtorch/commit/78221e8da9b3229bce63204629633eb602bba86c) is ignored.
v0.2.0 doesn't crush app.

What kind of measures should I take?

**Comment by raedle** [comment] 2022-08-24 05:53
@SomaKishimoto, thanks for reporting this issue. Can you share the canvas drawing source code?

If the canvas context is used in a rendering loop, then my hunch is that it is missing the `ctx.clear()` call at the beginning of loop

**Comment by SomaKishimoto** [comment] 2022-08-24 08:47
@raedle , thanks for your prompt reply.
`ctx.clear()` is not used as you mentioned because [the status](https://github.com/facebookresearch/playtorch/blob/main/react-native-pytorch-core/src/CanvasView.tsx#L229-L234) is deprecated. 
Is this status going to change? and, is there any example instructed to use `ctx.clear()`?

we refer to [this example](https://github.com/facebookresearch/playtorch/blob/main/react-native-pytorch-core/example/src/toolbox/models/DETR.tsx) and do continuous rendering with `onFrame` instead of `onCapture`

**Comment by raedle** [comment] 2022-08-26 05:29
@SomaKishimoto, there is an issue with the recent change to the iOS canvas. We are investigating on a forward fix. In the meantime, the `ctx.clear()` will circumvent possible memory issues. Can you give it a try if this unblocks you?

**Comment by SomaKishimoto** [comment] 2022-08-26 07:45
@raedle , thanks! We'll try it and let you know if there is any progress!

**Comment by SomaKishimoto** [comment] 2022-08-26 08:39
Works fine, @raedle! Thanks a lot.

**Comment by raedle** [comment] 2022-09-06 23:08
Thanks for reporting back. Closing task!

**Closed by raedle** 2022-09-06 23:08 UTC
Labels: 🐛 bug, 🍏 ios

**Comment by SomaKishimoto** [comment] 2022-09-07 06:47
@raedle , Unfortunately, repeated rendering crashes app on  **iPad Air Gen3 (OS15.5)** after running for 4 hours.
The error code is below
`Error: W0907 14:44:28.448568 1850142720 JSIExecutor.cpp:381] Memory warning (pressure level: 1) received by JS VM, unrecognized pressure level`

I confirmed that the app was working for at least 9 hours on iPhone.
However, I didn't check if it works more than 9 hours, so I'll check it.

**Comment by raedle** [comment] 2022-09-08 06:42
@SomaKishimoto, thanks for reporting the memory warning. Can you provide more info on the following three questions?

* Is the Hermes or JSC enabled as JavaScript Runtime? You can check with the following code

```javascript
const isHermes = () => !!global.HermesInternal;
```

https://reactnative.dev/docs/hermes#confirming-hermes-is-in-use

* Is the app running in debug or release mode?
* Do you have a crash log that you can share?

**Comment by SomaKishimoto** [comment] 2022-09-09 02:15
@raedle , thanks for your prompt reply. 
the answers to your questions are as follows.
* Hermes is true 
* release mode
* No further information than the log I shared before
 
It's me that brought this question up, but this problem may be caused by something else.
I'll report back if there seems to be a problem with Playtorch.

**Comment by raedle** [comment] 2022-09-09 02:57
Thanks @SomaKishimoto, and please let us know if the issue is with PlayTorch!
